#======================================================================
# Project settings
#======================================================================
branches:
  only:
    - develop

env:
  - BUILD_TYPE=Debug

language: cpp

services:
  - docker

cache:
  ccache: true
  directories:
  - $HOME/repo.cache

git:
  lfs_skip_smudge: true

#======================================================================
#======================================================================
before_install:
  - |
    # setup the configurables that the subsequent scripts use

    # see .travis/prep.sh for a full description of these env vars
    export BUNDLE_URL="https://github.com/JCSDA/soca-bundle.git"
    export MAIN_REPO=soca
    export MAIN_BUILD_TYPE=${BUILD_TYPE}    
    export LIB_REPOS="fms cvmix geokdtree mom6_da_hooks gsw mom6
                      fckit saber oops ioda ufo ioda-converters soca-config"
    export LIB_BUILD_TYPE=RelWIthDebInfo
    export LIB_BUILD_OPT_OOPS="-DENABLE_OOPS_TOYMODELS=OFF"
    export MATCH_REPOS="saber oops ioda ioda-converters ufo soca soca-config"
    export LFS_REPOS="soca"

    export BRANCH=$( [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && \
                     echo $TRAVIS_BRANCH || echo $TRAVIS_PULL_REQUEST_BRANCH )
    export_vars="-e REPO_CACHE=/repo.cache -e LIB_REPOS -e LIB_BUILD_TYPE 
                 -e MAIN_REPO -e MAIN_BUILD_TYPE -e CCACHE_DIR=/ccache
                 -e LIB_BUILD_OPT_OOPS"
        
  - |
    # clone and prep the repos
    WORK_DIR=$HOME/work
    mkdir -p $WORK_DIR; cd $WORK_DIR
    REPO_CACHE=$HOME/repo.cache ${TRAVIS_BUILD_DIR}/.travis/prep.sh

  - |
    # alter file permissions
    chmod 777 -R ~/.ccache
    chmod 777 -R $HOME/repo.cache
    cd ${WORK_DIR} && find . -name \* -exec chmod 777 {} \;

  - |
    # prepare docker image from jcsda/docker:latest
    cd ${TRAVIS_BUILD_DIR}/.travis
    docker build -t jcsda/dockerl2 --build-arg=Dockerfile .
    docker images
    ci_env=`bash <(curl -s https://codecov.io/env)`
    docker run -d -t $ci_env $export_vars \
      -v ${WORK_DIR}:/jcsda/work \
      -v $HOME/.ccache:/ccache \
      -v $HOME/repo.cache:/repo.cache \
      --name jcsda_container jcsda/dockerl2
    docker ps -a


#======================================================================
# Here are the run steps
#======================================================================
script:
  - |
    # Build code
    docker exec jcsda_container bash \
     -c 'cd /jcsda/work && /jcsda/work/repo.src/soca/.travis/build.sh'

  - |
    # run tests
    docker exec jcsda_container bash \
     -c 'cd /jcsda/work/repo.build/soca && ctest --output-on-failure'

  - |
    # upload code coverage
    docker exec jcsda_container bash \
     -c 'cd /jcsda/work/repo.src/soca && lcov -c -d . -d ../../repo.build/soca/ -o coverage.info  --no-external -q && bash <(curl -s https://codecov.io/bash)'