geometry:
  mom6_input_nml: ./inputnml/input.nml
  fields metadata: ./fields_metadata.yml

model:
  name: SOCA
  tstep: PT1H
  advance_mom6: 1
  model variables: &soca_vars [socn, tocn, ssh, hocn]

initial condition:
  read_from_file: 1
  date: &date 2018-04-15T00:00:00Z
  basename: ./INPUT/
  ocn_filename: MOM.res.nc
  state variables:  *soca_vars

forecast length: P1D

output:
  frequency: PT1H
  datadir: fcst
  exp: mom6
  date: *date
  type: fc
