geometry:
  mom6_input_nml: ./inputnml/input.nml
  fields metadata: ./fields_metadata.yml

model:
  name: SOCA
  tstep: PT1H
  advance_mom6: 1
  model variables: &model_vars [socn, tocn, ssh, hocn, mld, layer_depth]

initial condition:
  read_from_file: 1
  basename: ./INPUT/
  ocn_filename: MOM.res.nc
  ice_filename: cice.res.nc
  date: &date 2018-04-15T00:00:00Z
  state variables: *model_vars

background error:
  covariance model: SocaError
  date: *date
  analysis variables: &soca_vars [socn, tocn, ssh, hocn]
  bump:
    io:
      data directory: ./bump
    drivers:
      multivariate strategy: specific_univariate
      read local nicas: 1
  perturbation scales:
    tocn:  10.0
    socn:  10.0
    ssh:   0.0
  correlation:
  - name: ocn
    variables: [tocn, ssh, socn]

  variable changes:

  - variable change: VertConvSOCA
    Lz_min: 2.0
    Lz_mld: 1
    Lz_mld_max: 500.0
    scale_layer_thick: 1.5
    input variables: *soca_vars
    output variables: *soca_vars

  - variable change: BkgErrFILT
    ocean_depth_min: 1000 # [m]
    rescale_bkgerr: 1.0
    efold_z: 2500.0       # [m]
    input variables: *soca_vars
    output variables: *soca_vars

  - variable change: BkgErrGODAS
    t_min: 0.25
    t_max: 1.0
    t_dz:  20.0
    t_efold: 500.0
    s_min: 0.0
    s_max: 0.25
    ssh_min: 0.0   # value at EQ
    ssh_max: 0.0   # value in Extratropics
    ssh_phi_ex: 20 # lat of transition from extratropics
    cicen_min: 0.1
    cicen_max: 0.5
    hicen_min: 10.0
    hicen_max: 100.0
    chl_min: 0.001
    chl_max: 30.0
    biop_min: 0.0
    biop_max: 1.0e-6
    input variables: *soca_vars
    output variables: *soca_vars

  - variable change: BalanceSOCA
    dsdtmax: 0.1
    dsdzmin: 3.0e-6
    dtdzmin: 1.0e-6
    nlayers: 1
    input variables: *soca_vars
    output variables: *soca_vars

members: 1
perturbed variables: *soca_vars
forecast length: PT0H

output:
 frequency: PT1H
 datadir: out
 exp: pert
 type: ens
 date: *date
