geometry:
  mom6_input_nml: ./inputnml/input.nml
  fields metadata: ./fields_metadata.yml

analysis variables: &ana_vars [socn, tocn, ssh]

background:
  read_from_file: 1
  date: &date 2018-04-15T00:00:00Z
  basename: ./INPUT/
  ocn_filename: MOM.res.nc
  ice_filename: cice.res.nc
  wav_filename: wav.res.nc
  state variables: [hocn, socn, tocn, ssh]

background error:
  covariance model: SocaError
  analysis variables: *ana_vars
  date: *date
  bump:
    verbosity: main
    datadir: ./bump
    method: cor
    strategy: specific_univariate
    new_nicas: 1
    write_nicas_local: 1
    mask_check: 1
    resol: 20.0
    network: 0 # Not re-implemented yet
  correlation:
  - name: ocn
    base value: 300.0e3
    rossby mult: 1.0
    min grid mult: 2.0
    min value: 200.0e3
    variables: [tocn, socn, ssh]
