forecast length: P5D
window begin: 2018-04-15T00:00:00Z
window length: P5D

geometry:
  mom6_input_nml: ./inputnml/input.nml
  fields metadata: ./fields_metadata.yml

model:
  name: SOCA
  tstep: PT1H
  advance_mom6: 1
  model variables: &soca_vars [socn, tocn, ssh, hocn]

initial condition:
  read_from_file: 1
  date: 2018-04-15T00:00:00Z
  basename: ./INPUT/
  ocn_filename: MOM.res.nc
  state variables: *soca_vars

make obs: true

observations:
  - obs space:
      name: SeaSurfaceTemp
      obsdatain:  {obsfile: ./obs_scratch/sst.nc4}
      obsdataout: {obsfile: ./obs_scratch/sst.out.nc4}
      simulated variables: [sea_surface_temperature]
    obs operator:
      name: Identity

  - obs space:
      name: SeaSurfaceSalt
      obsdatain:  {obsfile: ./obs_scratch/sss.nc4}
      obsdataout: {obsfile: ./obs_scratch/sss.out.nc4}
      simulated variables: [sea_surface_salinity]
    obs operator:
      name: Identity

  - obs space:
      name: ADT
      obsdatain:  {obsfile: ./obs_scratch/adt.nc4}
      obsdataout: {obsfile: ./obs_scratch/adt.out.nc4}
      simulated variables: [obs_absolute_dynamic_topography]
    obs operator:
      name: ADT

  - obs space:
      name: InsituTemperature
      obsdatain:  {obsfile: ./obs_scratch/insitu.T.nc4}
      obsdataout: {obsfile: ./obs_scratch/insitu.T.out.nc4}
      simulated variables: [sea_water_temperature]
    obs operator:
      name: InsituTemperature

  - obs space:
      name: InsituSalinity
      obsdatain:  {obsfile: ./obs_scratch/insitu.S.nc4}
      obsdataout: {obsfile: ./obs_scratch/insitu.S.out.nc4}
      simulated variables: [sea_water_salinity]
    obs operator:
      name: MarineVertInterp
