#pragma once

// This file defines what appears on the Main Page of the documentation
// generated by doxygen. The file contains no code, and does not appear
// in any cpp include statement.
//
/*!
 * \mainpage SOCA MOM6 Interface to JEDI
 *
 * SOCA is the interface between the generic components of the JEDI system and MOM6.
 * MOM6 is developed by NOAA's Geophysical Fluid Dynamics Laboratory (GFDL).
 */